version: '3.8'

services:
  discovery-service:
    build:
      context: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - typesmart-net

  suggestion-service:
    build:
      context: ./suggestion-service
    container_name: suggestion-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - typesmart-net

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - suggestion-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - typesmart-net

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080
    container_name: typesmart-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - typesmart-net

networks:
  typesmart-net:
    driver: bridge